- name: Ensure PostgreSQL databases exist
  community.postgresql.postgresql_db:
    login_host: "{{ ansible_host }}"
    login_user: "{{ rds_postgres_user }}"
    login_password: "{{ rds_postgres_password }}"
    login_port: "{{ postgres_port }}"
    name: "{{ item }}"
    owner: "{{ rds_postgres_user }}"
    state: present
  loop: "{{ postgres_databases }}"
  become: no
  delegate_to: localhost