services:
  # Keycloak Database
  keycloak-db:
    image: postgres:17
    container_name: keycloak-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak123
    volumes:
      - keycloak-postgres-data:/var/lib/postgresql/data
    networks:
      - infra-net

  # Keycloak Server
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.1
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak123
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
    ports:
      - "8080:8080"
    command:
      - start-dev
    depends_on:
      - keycloak-db
    networks:
      - infra-net

  # Event Seating PostgreSQL
  event-seating-db:
    image: postgres:17
    container_name: event-seating-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: event_seating
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - event-seating-postgres-data:/var/lib/postgresql/data
    networks:
      - infra-net

  # Localstack for S3
  event-seating-localstack:
    image: localstack/localstack:latest
    container_name: event-seating-localstack
    environment:
      - DEBUG=1
      - USE_SSL=0
      - AWS_CBOR_DISABLE=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME=localstack
      - SERVICES=s3
      - AWS_DEFAULT_REGION=us-east-1
    ports:
      - '4566-4583:4566-4583'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./script/localstack/s3/init-s3-bucket.sh:/etc/localstack/init/ready.d/init-s3-bucket.sh
    networks:
      - infra-net

  # Redis for caching
  redis:
    image: redis:latest
    container_name: event-seating-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - infra-net

volumes:
  keycloak-postgres-data:
  event-seating-postgres-data:
  redis-data:

networks:
  infra-net:
    driver: bridge
