services:
  # Keycloak Database
  keycloak-db:
    image: postgres:17
    container_name: keycloak-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak123
    volumes:
      - keycloak-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - infra-net

  # Keycloak Server
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.1
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak123
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HOSTNAME: auth.ticketly.com
    ports:
      - "8080:8080"
    command: start-dev
    depends_on:
      keycloak-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/localhost/8080 && exec 3<&- && exec 3>&-"]
      interval: 15s
      timeout: 5s
      retries: 10
    networks:
      - infra-net

  # Event Seating PostgreSQL
  event-seating-db:
    image: postgres:17
    container_name: event-seating-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: event_seating
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command: postgres -c wal_level=logical
    volumes:
      - event-seating-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - infra-net

  order-service-db:
    image: postgres:15
    container_name: order_service_db
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: secretpass
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - order-service-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d appdb"]
      interval: 5s
      retries: 5

  payment-service-db:
    image: mysql:8.0
    container_name: payment_service_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: payment_gateway
      MYSQL_USER: payment_user
      MYSQL_PASSWORD: payment_pass
    ports:
      - "3306:3306"
    volumes:
      - payment-service-db-data:/var/lib/mysql
      - ./scripts/mysql-init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-ppassword"]
      interval: 30s
      timeout: 10s
      retries: 5
    command: --default-authentication-plugin=mysql_native_password

  # MongoDB for Query Service
  query-db:
    image: mongo:latest
    container_name: query-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - infra-net
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching
  redis:
    image: redis:latest
    container_name: event-seating-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - infra-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Kafka Broker in KRaft mode
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    ports:
      - "9092:9092"
    volumes:
      - kafka-data:/var/lib/kafka/data
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://localhost:9092,PLAINTEXT://kafka:29092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_LISTENERS: 'PLAINTEXT_HOST://0.0.0.0:9092,PLAINTEXT://0.0.0.0:29092,CONTROLLER://kafka:9093'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    networks:
      - infra-net
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 15s
      timeout: 10s
      retries: 10

  # Kafka UI for easy topic management and message browsing
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "9000:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - infra-net

  # Debezium for Change Data Capture (CDC)
  debezium-connect:
    image: debezium/connect:2.5
    container_name: debezium-connect
    ports:
      - "8083:8083"
    depends_on:
      kafka:
        condition: service_healthy
      event-seating-db:
        condition: service_healthy
    environment:
      BOOTSTRAP_SERVERS: kafka:29092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
    networks:
      - infra-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/"]
      interval: 10s
      timeout: 5s
      retries: 10

  # Debezium connector registration service
  debezium-connector-init:
    image: curlimages/curl:latest
    container_name: debezium-connector-init
    depends_on:
      debezium-connect:
        condition: service_healthy
    volumes:
      - ./debezium:/debezium
    command: >
      sh -c "
        echo 'Waiting for Debezium Connect to start...' &&
        sleep 30 &&
        curl -X POST -H 'Content-Type: application/json' --data @/debezium/debezium.json http://debezium-connect:8083/connectors &&
        echo 'Connector registration complete!'
      "
    networks:
      - infra-net

  # API Gateway
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8088:8088"
    environment:
      - KEYCLOAK_ISSUER_URI=http://auth.ticketly.com:8080/realms/event-ticketing
      - KEYCLOAK_JWK_SET_URI=http://auth.ticketly.com:8080/realms/event-ticketing/protocol/openid-connect/certs
      - EVENT_SEATING_SERVICE_URI=http://host.docker.internal:8081
      - EVENT_QUERY_SERVICE_URI=http://host.docker.internal:8082
      - TICKET_SERVICE_URI=http://host.docker.internal:8084
      - PAYMENT_SERVICE_URI=http://host.docker.internal:8085
    depends_on:
      keycloak:
        condition: service_healthy
    networks:
      - infra-net
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "auth.ticketly.com:host-gateway"

  # Go Scheduler Service
  scheduler-service:
    image: ticketly/scheduler-service:latest
    container_name: scheduler-service
    depends_on:
      keycloak:
        condition: service_healthy
    environment:
      - EVENT_SERVICE_URL=http://host.docker.internal:8081/api/event-seating
      - KEYCLOAK_URL=http://auth.ticketly.com:8080
      - SCHEDULER_CLIENT_SECRET=${SCHEDULER_CLIENT_SECRET}
      - SQS_QUEUE_URL=https://sqs.us-east-1.amazonaws.com/964191654724/session-on-sale-queue
    volumes:
      - ~/.aws:/root/.aws:ro
    networks:
      - infra-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Event Seating Service
  event-command-service:
    image: ticketly/event-command-service:latest
    container_name: event-command-service
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
      - DATABASE_URL=jdbc:postgresql://event-seating-db:5432/event_seating
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - JWT_ISSUER_URI=http://auth.ticketly.com:8080/realms/event-ticketing
      - JWT_JWK_SET_URI=http://auth.ticketly.com:8080/realms/event-ticketing/protocol/openid-connect/certs
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - AWS_REGION=us-east-1
      - AWS_SQS_QUEUE_ARN=arn:aws:sqs:us-east-1:964191654724:session-on-sale-queue
      - AWS_SCHEDULER_ROLE_ARN=arn:aws:iam::964191654724:role/EventBridgeSchedulerSqsRole
      - AWS_SCHEDULER_GROUP_NAME=event-ticketing-schedules
      - SHOW_SQL=false
      - LOG_LEVEL_APP=DEBUG
      - LOG_LEVEL_SECURITY=WARN
    depends_on:
      event-seating-db:
        condition: service_healthy
      redis:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    networks:
      - infra-net
    volumes:
      - ~/.aws:/root/.aws:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api/event-seating/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    extra_hosts:
      - "auth.ticketly.com:host-gateway"

# Event Query Service
  event-query-service:
    image: ticketly/event-query-service:latest
    container_name: event-query-service
    ports:
      - "8082:8082"
    depends_on:
      query-db:
        condition: service_healthy
      kafka:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    environment:
      - MONGODB_URI=mongodb://query-db:27017/event-seating
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - KEYCLOAK_ISSUER_URI=http://auth.ticketly.com:8080/realms/event-ticketing
      - COMMAND_SERVICE_URL=http://host.docker.internal:8081/api/event-seating
      - EVENT_PROJECTION_CLIENT_SECRET=${EVENT_PROJECTION_CLIENT_SECRET}
      - KEYCLOAK_ISSUER_URI=http://auth.ticketly.com:8080/realms/event-ticketing
      - KEYCLOAK_JWK_SET_URI=http://auth.ticketly.com:8080/realms/event-ticketing/protocol/openid-connect/certs
      - KAFKA_GROUP_ID=event-query-service
    networks:
      - infra-net
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "auth.ticketly.com:host-gateway"

volumes:
  keycloak-postgres-data:
  event-seating-postgres-data:
  redis-data:
  kafka-data:
  mongo-data:
  order-service-postgres-data:
  payment-service-db-data:

networks:
  infra-net:
    driver: bridge
