services:
  # Keycloak Database
  keycloak-db:
    image: postgres:17
    container_name: keycloak-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak123
    volumes:
      - keycloak-postgres-data:/var/lib/postgresql/data
    networks:
      - infra-net

  # Keycloak Server
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.1
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak123
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
    ports:
      - "8080:8080"
    command:
      - start-dev
    depends_on:
      - keycloak-db
    networks:
      - infra-net

  # Event Seating PostgreSQL
  event-seating-db:
    image: postgres:17
    container_name: event-seating-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: event_seating
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command: postgres -c wal_level=logical
    volumes:
      - event-seating-postgres-data:/var/lib/postgresql/data
    networks:
      - infra-net

  # Localstack for AWS Services
  event-seating-localstack:
    image: localstack/localstack:latest
    container_name: event-seating-localstack
    environment:
      - DEBUG=1
      - SERVICES=s3,sqs,scheduler,iam
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PERSISTENCE=1
    ports:
      - '4566:4566'
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./scripts/localstack:/etc/localstack/init/ready.d"
      - "./scripts/localstack/scheduler-role-policy.json:/etc/localstack/init/ready.d/scheduler-role-policy.json"
      - localstack-data:/var/lib/localstack
    networks:
      - infra-net

  # Redis for caching
  redis:
    image: redis:latest
    container_name: event-seating-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - infra-net

  # Kafka Broker in KRaft mode
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    ports:
      - "9092:9092"
    volumes:
      - kafka-data:/var/lib/kafka/data
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://localhost:9092,PLAINTEXT://kafka:29092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_LISTENERS: 'PLAINTEXT_HOST://0.0.0.0:9092,PLAINTEXT://0.0.0.0:29092,CONTROLLER://kafka:9093'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk' # A pre-generated cluster ID
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
    networks:
      - infra-net

  # Debezium for Change Data Capture (CDC)
  debezium-connect:
    image: debezium/connect:2.5
    container_name: debezium-connect
    ports:
      - "8083:8083"
    depends_on:
      - kafka
      - event-seating-db
    environment:
      BOOTSTRAP_SERVERS: kafka:29092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
    networks:
      - infra-net

  # Debezium connector registration service
  debezium-connector-init:
    image: curlimages/curl:latest
    container_name: debezium-connector-init
    depends_on:
      - debezium-connect
    volumes:
      - ./debezium:/debezium
    command: >
      sh -c "
        echo 'Waiting for Debezium Connect to start...' &&
        sleep 30 &&
        curl -X POST -H 'Content-Type: application/json' --data @/debezium/debezium.json http://debezium-connect:8083/connectors &&
        echo 'Connector registration complete!'
      "
    networks:
      - infra-net

  # API Gateway
  api-gateway:
    # This tells Docker to build the image from the Dockerfile
    build: ./api-gateway 
    container_name: api-gateway
    ports:
      - "8088:8088" # The frontend will talk to this port
    networks:
      - infra-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  keycloak-postgres-data:
  event-seating-postgres-data:
  redis-data:
  kafka-data:
  localstack-data:

networks:
  infra-net:
    driver: bridge
