version: '3.8'

services:
  keycloak-db:
    image: postgres:17
    container_name: keycloak-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - infra-net

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.1
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak123
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
    ports:
      - "8080:8080"
    command:
      - start-dev
    depends_on:
      - keycloak-db
    networks:
      - infra-net
    
  # LocalStack configuration
  # localstack:
  #   container_name: localstack
  #   image: localstack/localstack:latest
  #   environment:
  #     - DEBUG=1
  #     - USE_SSL=0
  #     - AWS_CBOR_DISABLE=1
  #     - DOCKER_HOST=unix:///var/run/docker.sock
  #     - HOSTNAME=localstack
  #     - SERVICES=s3
  #     - AWS_DEFAULT_REGION=us-east-1
  #   ports:
  #     - '4566-4583:4566-4583'
  #   volumes:
  #     - ${TEMPDIR:-/tmp/localstack}:/tmp/localstack
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - ./script/localstack/s3/init-s3-bucket.sh:/docker-entrypoint-initaws.d/init-s3-bucket.sh

volumes:
  postgres_data:

networks:
  infra-net:
    driver: bridge
