server:
  port: 8089

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/event-ticketing

  cloud:
    gateway:
      server:
        webflux:
          #          default-filters:
          #            - TokenRelay
          routes:
            - id: event_seating_service_route
              uri: http://localhost:8081
              predicates:
                - Path=/api/event-seating/**
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: "http://localhost:8090"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders: '*'
                allowCredentials: true
            add-to-simple-url-handler-mapping: true