server:
  port: 8088

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/event-ticketing}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8080/realms/event-ticketing/protocol/openid-connect/certs}
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: event_seating_service_route
              uri: ${EVENT_SEATING_SERVICE_URI:http://localhost:8081}
              predicates:
                - Path=/api/event-seating/**
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: "http://localhost:8090"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE

# Detailed logging configuration for development
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty: DEBUG
    reactor.netty.http.client: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
