server:
  port: 8088

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/event-ticketing
          jwk-set-uri: http://keycloak:8080/realms/event-ticketing/protocol/openid-connect/certs
  cloud:
    gateway:
      routes:
        - id: event_seating_service_route
          uri: http://host.docker.internal:8081
          predicates:
            - Path=/api/event-seating/**

# Minimal logging configuration for basic request tracking
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.security: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
