server:
  port: 8088

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://host.docker.internal:8080/realms/event-ticketing

  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - TokenRelay
          routes:
            - id: event_seating_service_route
              uri: http://host.docker.internal:8081
              predicates:
                - Path=/api/event-seating/**