apiVersion: v1
kind: Secret
metadata:
  name: ticketly-google-private-key
  namespace: ticketly
type: Opaque
stringData:
  GOOGLE_PRIVATE_KEY: |-
    -----BEGIN PRIVATE KEY-----
    REPLACE_ME
    -----END PRIVATE KEY-----
