apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ticketly-api
  namespace: ticketly
spec:
  ingressClassName: traefik
  rules:
    - host: api.dpiyumal.me
      http:
        paths:
          - path: /api/event-seating
            pathType: Prefix
            backend:
              service:
                name: event-command-service
                port:
                  number: 8081
          - path: /api/event-query
            pathType: Prefix
            backend:
              service:
                name: event-query-service
                port:
                  number: 8082
          - path: /api/order
            pathType: Prefix
            backend:
              service:
                name: order-service
                port:
                  number: 8084
          - path: /api/scheduler
            pathType: Prefix
            backend:
              service:
                name: scheduler-service
                port:
                  number: 8085
