apiVersion: apps/v1
kind: Deployment
metadata:
  name: debezium-connect
  namespace: ticketly
  labels:
    app: debezium-connect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debezium-connect
  template:
    metadata:
      labels:
        app: debezium-connect
    spec:
      containers:
        - name: debezium-connect
          image: debezium/connect:2.5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          env:
            - name: BOOTSTRAP_SERVERS
              value: ticketly-kafka:9092
            - name: GROUP_ID
              value: "1"
            - name: CONFIG_STORAGE_TOPIC
              value: my_connect_configs
            - name: OFFSET_STORAGE_TOPIC
              value: my_connect_offsets
            - name: STATUS_STORAGE_TOPIC
              value: my_connect_statuses
          readinessProbe:
            httpGet:
              path: /
              port: 8083
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8083
            initialDelaySeconds: 60
            periodSeconds: 20
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: debezium-connect
  namespace: ticketly
  labels:
    app: debezium-connect
spec:
  selector:
    app: debezium-connect
  ports:
    - name: http
      port: 8083
      targetPort: 8083
  type: ClusterIP
