---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: microservices-daily-restart
  namespace: ticketly
  labels:
    app: microservices-restart
    purpose: maintenance
spec:
  # Schedule: Midnight Sri Lanka/Mumbai Time (UTC+5:30)
  # With timeZone set, this runs at 00:00 Asia/Colombo time
  schedule: "0 0 * * *"
  
  # Keep last 3 successful and 1 failed job for debugging
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  
  # Timezone support (requires Kubernetes 1.25+)
  # This makes the schedule interpret in local time, not UTC
  timeZone: "Asia/Colombo"
  
  # Concurrency policy - don't allow overlapping restarts
  concurrencyPolicy: Forbid
  
  # If job fails, retry up to 2 times
  jobTemplate:
    spec:
      backoffLimit: 2
      # Jobs should complete within 20 minutes (4 deployments * 5min = 20min buffer)
      activeDeadlineSeconds: 1200
      
      template:
        metadata:
          labels:
            app: microservices-restart
            job-type: scheduled-maintenance
        shttps://gamma.app/signinpec:
          serviceAccountName: deployment-restarter
          restartPolicy: OnFailure
          
          containers:
            - name: kubectl-restarter
              image: bitnami/kubectl:latest
              imagePullPolicy: IfNotPresent
              
              command:
                - /bin/bash
                - -c
                - |
                  set -euo pipefail
                  
                  echo "=========================================="
                  echo "Starting microservices rollout restart"
                  echo "Time: $(date)"
                  echo "=========================================="
                  echo ""
                  
                  # List of deployments to restart
                  DEPLOYMENTS=(
                    "event-command-service"
                    "event-query-service"
                    "order-service"
                    "scheduler-service"
                  )
                  
                  # Track success/failure
                  FAILED=0
                  SUCCEEDED=0
                  
                  # Phase 1: Trigger all rollout restarts in parallel
                  echo "Phase 1: Initiating restarts for all services..."
                  echo ""
                  
                  for deployment in "${DEPLOYMENTS[@]}"; do
                    echo "┌─────────────────────────────────────────"
                    echo "│ Triggering restart: $deployment"
                    echo "└─────────────────────────────────────────"
                    
                    # Check if deployment exists
                    if ! kubectl get deployment "$deployment" -n ticketly &>/dev/null; then
                      echo "⚠️  WARNING: Deployment '$deployment' not found. Skipping..."
                      echo ""
                      continue
                    fi
                    
                    # Perform rollout restart (don't wait)
                    if kubectl rollout restart deployment/"$deployment" -n ticketly; then
                      echo "✓ Initiated restart for $deployment"
                    else
                      echo "✗ Failed to initiate restart for $deployment"
                      ((FAILED++))
                    fi
                    echo ""
                  done
                  
                  echo "=========================================="
                  echo "Phase 2: Waiting for all rollouts to complete..."
                  echo "=========================================="
                  echo ""
                  
                  # Phase 2: Wait for all rollouts to complete
                  for deployment in "${DEPLOYMENTS[@]}"; do
                    # Skip if deployment doesn't exist
                    if ! kubectl get deployment "$deployment" -n ticketly &>/dev/null; then
                      continue
                    fi
                    
                    echo "Waiting for: $deployment"
                    
                    # Wait for rollout to complete (timeout: 3 minutes per service)
                    if kubectl rollout status deployment/"$deployment" -n ticketly --timeout=3m; then
                      echo "✓ Successfully restarted $deployment"
                      ((SUCCEEDED++))
                    else
                      echo "✗ Failed to complete rollout for $deployment (timeout or error)"
                      ((FAILED++))
                    fi
                    echo ""
                  done
                  
                  echo "=========================================="
                  echo "Restart Summary"
                  echo "=========================================="
                  echo "Succeeded: $SUCCEEDED"
                  echo "Failed: $FAILED"
                  echo "Completed at: $(date)"
                  echo "=========================================="
                  
                  # Exit with error if any deployment failed
                  if [ "$FAILED" -gt 0 ]; then
                    echo ""
                    echo "❌ Some deployments failed to restart"
                    exit 1
                  fi
                  
                  echo ""
                  echo "✅ All deployments restarted successfully"
                  exit 0
              
              resources:
                requests:
                  cpu: 50m
                  memory: 64Mi
                limits:
                  cpu: 100m
                  memory: 128Mi
