export const devConfig = {
    eventCommandServiceUrl: 'http://localhost:8081/api/event-seating',
    eventQueryServiceUrl: 'http://localhost:8082/api/event-query',
    ticketsOrderServiceUrl: 'http://localhost:8084/api/order',
    keycloakTokenUrl: 'http://localhost:8080/realms/event-ticketing/protocol/openid-connect/token',
    keycloakClientId: 'login-testing',
    username: 'test_user@yopmail.com',
    password: 'test123',
    adminUsername: 'admin@yopmail.com',
    adminPassword: 'admin123',
    postgresEventDbUrl: 'postgres://ticketly:ticketly@localhost:5432/event_service',
    postgresOrderDbUrl: 'postgres://ticketly:ticketly@localhost:5432/order_service',
    mongodbAddress: 'mongodb://localhost:27017',
    redisAddress: 'redis://localhost:6379',
};