export const prodConfig = {
    eventCommandServiceUrl: 'https://api.ticketly.com/api/event-seating',
    eventQueryServiceUrl: 'https://api.ticketly.com/api/event-query',
    ticketsOrderServiceUrl: 'https://api.ticketly.com/api/order',
    keycloakTokenUrl: 'https://auth.ticketly.com/realms/event-ticketing/protocol/openid-connect/token',
    keycloakClientId: 'login-testing',
    username: 'test_user@yopmail.com',
    password: 'test123',
    adminUsername: 'admin@yopmail.com',
    adminPassword: 'admin123',
    postgresEventDbUrl: 'postgres://ticketly:ticketly@db.ticketly.com:5432/event_service',
    postgresOrderDbUrl: 'postgres://ticketly:ticketly@db.ticketly.com:5432/order_service',
    mongodbAddress: 'mongodb://mongodb.ticketly.com:27017',
    redisAddress: 'redis://redis.ticketly.com:6379',
};