apiVersion: v1
kind: Secret
metadata:
  name: ticketly-secrets
  namespace: ticketly
type: Opaque
# These are placeholders - in a real environment use a proper secret management solution like Sealed Secrets, HashiCorp Vault, or Kubernetes External Secrets
data:
  DATABASE_USERNAME: BASE64_ENCODED_VALUE
  DATABASE_PASSWORD: BASE64_ENCODED_VALUE
  RDS_ENDPOINT: BASE64_ENCODED_VALUE
  EVENTS_SERVICE_CLIENT_SECRET: BASE64_ENCODED_VALUE
  EVENT_PROJECTION_CLIENT_SECRET: BASE64_ENCODED_VALUE
  SCHEDULER_CLIENT_SECRET: BASE64_ENCODED_VALUE
  TICKET_CLIENT_SECRET: BASE64_ENCODED_VALUE
  AWS_REGION: BASE64_ENCODED_VALUE
  AWS_S3_BUCKET_NAME: BASE64_ENCODED_VALUE
  AWS_ACCESS_KEY_ID: BASE64_ENCODED_VALUE
  AWS_SECRET_ACCESS_KEY: BASE64_ENCODED_VALUE
  QR_SECRET_KEY: BASE64_ENCODED_VALUE
  STRIPE_SECRET_KEY: BASE64_ENCODED_VALUE
  STRIPE_WEBHOOK_SECRET: BASE64_ENCODED_VALUE
  AWS_SQS_SESSION_SCHEDULING_ARN: BASE64_ENCODED_VALUE
  AWS_SQS_SESSION_SCHEDULING_URL: BASE64_ENCODED_VALUE
  AWS_SQS_TRENDING_JOB_ARN: BASE64_ENCODED_VALUE
  AWS_SQS_TRENDING_JOB_URL: BASE64_ENCODED_VALUE
  AWS_SQS_SESSION_REMINDERS_ARN: BASE64_ENCODED_VALUE
  AWS_SQS_SESSION_REMINDERS_URL: BASE64_ENCODED_VALUE
  AWS_SCHEDULER_ROLE_ARN: BASE64_ENCODED_VALUE
  AWS_SCHEDULER_GROUP_NAME: BASE64_ENCODED_VALUE
  SMTP_HOST: BASE64_ENCODED_VALUE
  SMTP_PORT: BASE64_ENCODED_VALUE
  SMTP_USERNAME: BASE64_ENCODED_VALUE
  SMTP_PASSWORD: BASE64_ENCODED_VALUE
  FROM_EMAIL: BASE64_ENCODED_VALUE
  FROM_NAME: BASE64_ENCODED_VALUE
  SCHEDULER_POSTGRES_DSN: BASE64_ENCODED_VALUE
  ORDER_POSTGRES_DSN: BASE64_ENCODED_VALUE
---
apiVersion: v1
kind: Secret
metadata:
  name: gcp-credentials
  namespace: ticketly
type: Opaque
data:
  gcp-credentials.json: BASE64_ENCODED_VALUE